---
      

- parted:
    device: /dev/sdc
    number: 2
    flags: [ lvm ]
    state: present
    part_end: 4GB

- filesystem:
    fstype: xfs
    dev: /dev/sdc1

- name: Create directory data1 if does not exist
  file:
    path: /part1
    state: directory
    mode: '0755'

- mount:
    fstype: xfs
    src: /dev/sdc1
    path: /part1
    state: mounted



- parted:
    device: /dev/sdc
    number: 2
    flags: [ lvm ]
    state: present
    part_start: 4.5GB
    part_end: 9GB


- filesystem:
    fstype: ext4
    dev: /dev/sdc2

- name: Create directory data1 if does not exist
  file:
    path: /part2
    state: directory
    mode: '0755'    


- mount:
    fstype: ext4
    src: /dev/sdc2
    path: /part2
    state: mounted